trigger:
- none

pool:
  name: agentpoolnew
  demands:
    - agent.name -equals agentl
  env:
  ANDROID_HOME: /home/azureuser/myagent/sdk/android-sdk
variables:
  ANDROID_HOME: /home/azureuser/myagent/sdk/android-sdk  # Path to your Android SDK
  PATH: $(ANDROID_HOME)/cmdline-tools/bin:$(ANDROID_HOME)/platform-tools:$(PATH)
steps:
- script: |
    echo $ANDROID_HOME
    ls $ANDROID_HOME
  displayName: 'Check ANDROID_HOME'


- task: FlutterBuild@0
  inputs:
    target: 'apk'
    projectDirectory: './'
    flutterDirectory: '/home/azureuser/myagent/sdk/flutter/bin'

