trigger:
- none

pool:
  name: agentpoolnew
  demands:
    - agent.name -equals agentl


steps:



- task: FlutterBuild@0
  inputs:
    target: 'apk'
    projectDirectory: './'
    flutterDirectory: '/home/azureuser/myagent/sdk/flutter/bin'

